// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YrZe6iN8OPzmmNNxtwzt-A4pcjoZq4o',
    appId: '1:308313028581:android:97eae734680d2db5a3610c',
    messagingSenderId: '308313028581',
    projectId: 'office-project-10c1a',
    storageBucket: 'office-project-10c1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKisgFQr1eCs7W_0WiBWxuX31HOuIMGhI',
    appId: '1:308313028581:ios:0f20d0a82aaf7d03a3610c',
    messagingSenderId: '308313028581',
    projectId: 'office-project-10c1a',
    storageBucket: 'office-project-10c1a.firebasestorage.app',
    iosBundleId: 'com.example.officeApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLMUgI8H7DWS1vaHkXYn03sFYEvm0WDhw',
    appId: '1:308313028581:web:aae22fdaf9279a35a3610c',
    messagingSenderId: '308313028581',
    projectId: 'office-project-10c1a',
    authDomain: 'office-project-10c1a.firebaseapp.com',
    storageBucket: 'office-project-10c1a.firebasestorage.app',
    measurementId: 'G-XNEGKHN79C',
  );

}